-- MySQL Script generated by MySQL Workbench
-- Mon Jun 29 14:56:22 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema aselfcheck
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aselfcheck
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aselfcheck` DEFAULT CHARACTER SET utf8 ;
USE `aselfcheck` ;

-- -----------------------------------------------------
-- Table `aselfcheck`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aselfcheck`.`products` (
  `product_id` INT NOT NULL,
  `product_name` VARCHAR(45) NULL,
  `product_price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`product_id`),
  UNIQUE INDEX `product_id_UNIQUE` (`product_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aselfcheck`.`cards_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aselfcheck`.`cards_info` (
  `card_id` INT NOT NULL,
  `card_number` VARCHAR(19) NOT NULL,
  PRIMARY KEY (`card_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aselfcheck`.`transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aselfcheck`.`transactions` (
  `transaction_id` INT NOT NULL AUTO_INCREMENT,
  `transaction_price` DECIMAL(10,2) NOT NULL,
  `transaction_date` DATE NULL,
  `cards_info_card_id` INT NOT NULL,
  PRIMARY KEY (`transaction_id`),
  INDEX `fk_transactions_cards_info_idx` (`cards_info_card_id` ASC) VISIBLE,
  CONSTRAINT `fk_transactions_cards_info`
    FOREIGN KEY (`cards_info_card_id`)
    REFERENCES `aselfcheck`.`cards_info` (`card_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aselfcheck`.`transactions_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aselfcheck`.`transactions_products` (
  `products_product_id` INT NOT NULL,
  `cards_info_card_id` INT NOT NULL,
  PRIMARY KEY (`products_product_id`, `cards_info_card_id`),
  INDEX `fk_products_has_cards_info_cards_info1_idx` (`cards_info_card_id` ASC) VISIBLE,
  INDEX `fk_products_has_cards_info_products1_idx` (`products_product_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_has_cards_info_products1`
    FOREIGN KEY (`products_product_id`)
    REFERENCES `aselfcheck`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_cards_info_cards_info1`
    FOREIGN KEY (`cards_info_card_id`)
    REFERENCES `aselfcheck`.`cards_info` (`card_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
